### ISSUE TITLE
Fix analytics app to use one top level query per subscription

### ISSUE THREAD

**Issue by tirumaraiselvan** [hasura/3factor-example#13]
Currently, analytics app is broken after upgrading Hasura from v0.31. 

Currently, we are using this subscription:

```
              subscription {
                number_orders {
                  count
                }
                number_order_validated {
                  count
                }
                number_order_payment_valid {
                  count
                }
                number_order_approved {
                  count
                }
                number_order_driver_assigned {
                  count
                }
              }
````

With latest Hasura (and as per GraphQL spec), we can have only one top level field in a subscription. This needs to be fixed by using multiple subscriptions.

**Comment by coco98** [comment]
@wawhal Do you think I can use namma graphql2chartjs for this chart?

**Comment by wawhal** [comment]
@coco98 we can. I can take this up.

**Comment by rikinsk** [comment]
needs update to: https://github.com/hasura/3factor-example/blob/master/src/analytics-app-frontend/src/App.js

**Comment by tirumaraiselvan** [comment]
Closed via https://github.com/hasura/3factor-example/pull/16
